Libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from pathlib import Path

from src.replace_censored_data import replace_censored

Load data

In [2]:
data_path = Path("../data/raw/synthetic_geochemistry_raw.csv")
df = pd.read_csv(data_path)

df.head(10)

,Br,Cl,F,SO4,Ca,Mg,Sr,Cu,Co,Pb,Zn,Li,Na,K,Mn,Fe,Ba,cluster_true
0,0.095899,0.062366,0.022015,0.127606,0.062787,0.084068,0.101009,0.016696,0.013143,0.018529,0.008178,0.073702,0.101234,0.049293,0.080354,0.039854,0.043268,A
1,0.099971,0.093327,0.017877,0.117157,0.060494,0.050880,0.050899,0.013455,0.025303,0.033002,0.016710,0.059443,0.140393,0.075276,0.055428,0.043988,0.046396,A
2,0.097458,0.112086,0.021785,0.102999,0.059963,0.030859,0.026210,0.009703,0.013486,0.033962,0.014224,0.067155,0.229360,0.091934,0.041578,0.027898,0.019340,A
3,0.131455,0.100846,0.023954,0.182852,0.073364,0.047819,0.016653,0.020484,0.014308,0.021735,0.033938,0.038828,0.117878,0.039912,0.039828,0.071948,0.024198,A
4,0.069935,0.084173,0.019400,0.114066,0.058589,0.046485,0.015482,0.008719,0.033469,0.017132,0.021410,0.097667,0.160111,0.092357,0.073442,0.056498,0.031067,A
5,0.078353,0.099664,0.033714,0.118878,0.065316,0.043945,0.019352,0.030324,0.032821,0.026388,0.011254,0.107708,0.111900,0.057874,0.056924,0.085164,0.020420,A
6,0.139627,0.136777,0.013133,0.050773,0.036093,0.075575,0.042134,0.009460,0.009850,0.015883,0.020120,0.075195,0.096866,0.081852,0.085998,0.085843,0.024821,A
7,0.104627,0.067142,0.011823,0.150891,0.038309,0.091525,0.049294,0.018152,0.023935,0.015690,0.009249,0.072828,0.175568,0.037389,0.016712,0.071969,0.044897,A
8,0.065775,0.109166,0.010385,0.147934,0.025342,0.056096,0.017875,0.012712,0.024498,0.013922,0.027306,0.131434,0.087283,0.070091,0.046787,0.090279,0.063114,A
9,0.074831,0.061395,0.021053,0.239808,0.127480,0.097977,0.046793,0.014006,0.008490,0.022728,0.011131,0.049308,0.087676,0.035773,0.031037,0.047629,0.022884,A

Check for zeros and Na's

In [3]:
df.isna().sum(), (df == 0).sum()

(Br              0
 Cl              0
 F               0
 SO4             0
 Ca              0
 Mg              0
 Sr              0
 Cu              0
 Co              0
 Pb              0
 Zn              0
 Li              0
 Na              0
 K               0
 Mn              0
 Fe              0
 Ba              0
 cluster_true    0
 dtype: int64,
 Br              0
 Cl              0
 F               0
 SO4             0
 Ca              0
 Mg              0
 Sr              0
 Cu              0
 Co              0
 Pb              0
 Zn              0
 Li              0
 Na              0
 K               0
 Mn              0
 Fe              0
 Ba              0
 cluster_true    0
 dtype: int64)

Replace censored data

In [ ]:
elements = [col for col in df.columns if col not in ["cluster_true"]]

df_clean = replace_censored(df, elements)
df_clean.head(10)

,Br,Cl,F,SO4,Ca,Mg,Sr,Cu,Co,Pb,Zn,Li,Na,K,Mn,Fe,Ba,cluster_true
0,0.095899,0.062366,0.022015,0.127606,0.062787,0.084068,0.101009,0.016696,0.013143,0.018529,0.008178,0.073702,0.101234,0.049293,0.080354,0.039854,0.043268,A
1,0.099971,0.093327,0.017877,0.117157,0.060494,0.050880,0.050899,0.013455,0.025303,0.033002,0.016710,0.059443,0.140393,0.075276,0.055428,0.043988,0.046396,A
2,0.097458,0.112086,0.021785,0.102999,0.059963,0.030859,0.026210,0.009703,0.013486,0.033962,0.014224,0.067155,0.229360,0.091934,0.041578,0.027898,0.019340,A
3,0.131455,0.100846,0.023954,0.182852,0.073364,0.047819,0.016653,0.020484,0.014308,0.021735,0.033938,0.038828,0.117878,0.039912,0.039828,0.071948,0.024198,A
4,0.069935,0.084173,0.019400,0.114066,0.058589,0.046485,0.015482,0.008719,0.033469,0.017132,0.021410,0.097667,0.160111,0.092357,0.073442,0.056498,0.031067,A
5,0.078353,0.099664,0.033714,0.118878,0.065316,0.043945,0.019352,0.030324,0.032821,0.026388,0.011254,0.107708,0.111900,0.057874,0.056924,0.085164,0.020420,A
6,0.139627,0.136777,0.013133,0.050773,0.036093,0.075575,0.042134,0.009460,0.009850,0.015883,0.020120,0.075195,0.096866,0.081852,0.085998,0.085843,0.024821,A
7,0.104627,0.067142,0.011823,0.150891,0.038309,0.091525,0.049294,0.018152,0.023935,0.015690,0.009249,0.072828,0.175568,0.037389,0.016712,0.071969,0.044897,A
8,0.065775,0.109166,0.010385,0.147934,0.025342,0.056096,0.017875,0.012712,0.024498,0.013922,0.027306,0.131434,0.087283,0.070091,0.046787,0.090279,0.063114,A
9,0.074831,0.061395,0.021053,0.239808,0.127480,0.097977,0.046793,0.014006,0.008490,0.022728,0.011131,0.049308,0.087676,0.035773,0.031037,0.047629,0.022884,A

Save processed data

In [5]:
out_path = Path("../data/processed/synthetic_geochemistry_clean.csv")
df_clean.to_csv(out_path, index=False)